CREATE DATABASE `fairy` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

-- cluster
CREATE TABLE IF NOT EXISTS `cluster` (
    cluster_id integer(4) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    group_id integer(4) NOT NULL,
    user_id integer(4) NOT NULL,
    cluster_name varchar(255) NOT NULL,
    seed TEXT NOT NULL,
    redis_mode varchar(25) NOT NULL,
    redis_version varchar(25) NOT NULL,
    image varchar(255) DEFAULT NULL,
    redis_password varchar(50) DEFAULT NULL,
    state varchar(50) NOT NULL,
    master_number integer(4) NOT NULL,
    node_number integer(4) NOT NULL,
    tag varchar(50) DEFAULT NULL,
    environment varchar(50) NOT NULL,
    import_type varchar(50) NOT NULL,
    info varchar(255) DEFAULT NULL,
    create_time datetime(0) NOT NULL,
    update_time datetime(0) NOT NULL,
    PRIMARY KEY (cluster_id),
    UNIQUE KEY (cluster_name)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;


-- node_info
CREATE TABLE IF NOT EXISTS node_info_${clusterId} (
    info_id integer(4) NOT NULL AUTO_INCREMENT,
    node varchar(50) NOT NULL,
    role varchar(50) NOT NULL,
    last_time tinyint(1) NOT NULL,
    response_time integer(4) NOT NULL,
    connected_clients bigint(20) NOT NULL,
    client_longest_output_list bigint(20) NOT NULL,
    client_biggest_input_buf bigint(20) NOT NULL,
    blocked_clients bigint(20) NOT NULL,
    used_memory bigint(20) NOT NULL,
    used_memory_rss bigint(20) NOT NULL,
    used_memory_overhead bigint(20) NOT NULL,
    used_memory_dataset bigint(20) NOT NULL,
    used_memory_dataset_perc double(6, 2) NOT NULL,
    mem_fragmentation_ratio double(6, 2) NOT NULL,
    total_connections_received bigint(20) NOT NULL,
    connections_received bigint(20) NOT NULL,
    rejected_connections bigint(20) NOT NULL,
    total_commands_processed bigint(20) NOT NULL,
    commands_processed bigint(20) NOT NULL,
    instantaneous_ops_per_sec bigint(20) NOT NULL,
    total_net_input_bytes bigint(20) NOT NULL,
    net_input_bytes bigint(20) NOT NULL,
    total_net_output_bytes bigint(40) NOT NULL,
    net_output_bytes bigint(20) NOT NULL,
    sync_full integer(4) NOT NULL,
    sync_partial_ok integer(4) NOT NULL,
    sync_partial_err integer(4) NOT NULL,
    sync_full_min integer(4) NOT NULL,
    sync_partial_ok_min integer(4) NOT NULL,
    sync_partial_err_min integer(4) NOT NULL,
    keyspace_misses bigint(20) NOT NULL,
    keyspace_hits bigint(20) NOT NULL,
    keyspace_hits_ratio double(6, 2) NOT NULL,
    used_cpu_sys double(20, 2) NOT NULL,
    cpu_sys double(20, 2) NOT NULL,
    used_cpu_user double(20, 2) NOT NULL,
    cpu_user double(20, 2) NOT NULL,
    `keys` integer(8) NOT NULL,
    `expires` integer(8) NOT NULL,
    `total_slow_log` integer(8) NOT NULL,
    `slow_log` integer(8) NOT NULL,
    update_time datetime(0) NOT NULL,
    PRIMARY KEY (info_id),
    INDEX multiple_query(last_time, node, update_time)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- slow_log
CREATE TABLE IF NOT EXISTS `slow_log` (
    slow_log_id integer(4) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
    cluster_id integer(4) NOT NULL,
    cluster_name varchar(255) NOT NULL,
    seed TEXT NOT NULL,
    redis_mode varchar(25) NOT NULL,
    os varchar(255) NOT NULL,
    redis_version varchar(25) NOT NULL,
    image varchar(255) DEFAULT NULL,
    redis_password varchar(50) DEFAULT NULL,
    state varchar(50) NOT NULL,
    master_number integer(4) NOT NULL,
    node_number integer(4) NOT NULL,
    tag varchar(50) DEFAULT NULL,
    environment varchar(50) NOT NULL,
    import_type varchar(50) NOT NULL,
    info varchar(255) NOT NULL,
    create_time datetime(0) NOT NULL,
    update_time datetime(0) NOT NULL,
    PRIMARY KEY (cluster_id),
    UNIQUE KEY (cluster_name)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;